### ISSUE TITLE
help:

### ISSUE THREAD

**Issue by rsaavy** [azeltov/adb_workshop#1]
Hello,

I've tried to follow this Readme.docx and I am unable to import a url when I want to add a new workspace. I also have downloaded the .dbc file and manual import into databricks environment. 

![image](https://user-images.githubusercontent.com/18731785/45367414-33565400-b5af-11e8-8301-030d2d71bbee.png)

![image](https://user-images.githubusercontent.com/18731785/45367456-49641480-b5af-11e8-982c-36f08529e8b5.png)

**Comment by rsaavy** [comment]
You can close the issue we got our data bricks demo to work for our Department

**Comment by ezwiefel** [comment]
Glad you got it working, @rsaavy. Closing this issue.
